version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
      POSTGRES_DB: rocket
    ports:
      - 5432:5432